name: Mirror to GitLab

on: [push]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Mirror Repository to GitLab
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/simsek.bl/cypress-techglobal-training.git"
